local module = {}

function module.checkApology(message, damagerName, targetName)
    local lowerMessage = string.lower(message)
    local lowerDamager = string.lower(damagerName)
    local lowerTarget = string.lower(targetName)
    
    local apologyPatterns = {
        "my bad " .. lowerTarget,
        "mb " .. lowerTarget,
        "im sorry " .. lowerTarget,
        "i'm sorry " .. lowerTarget,
        "sorry " .. lowerTarget,
        "apologies " .. lowerTarget,
        "my apologies " .. lowerTarget,
        "excuse me " .. lowerTarget,
        "pardon " .. lowerTarget,
        "pardon me " .. lowerTarget,
        "forgive me " .. lowerTarget,
        "my mistake " .. lowerTarget,
        "oops " .. lowerTarget,
        "whoops " .. lowerTarget,
        "my fault " .. lowerTarget,
        "that was my fault " .. lowerTarget,
        "i messed up " .. lowerTarget,
        "i made a mistake " .. lowerTarget,
        "i goofed " .. lowerTarget,
        "i slipped " .. lowerTarget,
        "i missed " .. lowerTarget,
        "i was wrong " .. lowerTarget,
        "my error " .. lowerTarget,
        "i apologize " .. lowerTarget,
        "i apologize to " .. lowerTarget,
        "sincere apologies " .. lowerTarget,
        "deepest apologies " .. lowerTarget,
        "my sincerest apologies " .. lowerTarget,
        "i take full responsibility " .. lowerTarget,
        "that's on me " .. lowerTarget,
        "my bad for " .. lowerTarget,
        "sorry about that " .. lowerTarget,
        "sorry for that " .. lowerTarget,
        "my bad for that " .. lowerTarget,
        "mb for " .. lowerTarget,
        "im sorry for " .. lowerTarget,
        "i'm sorry for " .. lowerTarget,
        "sorry for " .. lowerTarget,
        "apologies for " .. lowerTarget,
        "my apologies for " .. lowerTarget,
        "excuse me for " .. lowerTarget,
        "pardon for " .. lowerTarget,
        "forgive me for " .. lowerTarget,
        "my mistake for " .. lowerTarget,
        "my fault for " .. lowerTarget,
        "i messed up with " .. lowerTarget,
        "i made a mistake with " .. lowerTarget,
        "i goofed with " .. lowerTarget,
        "i slipped with " .. lowerTarget,
        "i missed with " .. lowerTarget,
        "i was wrong with " .. lowerTarget,
        "my error with " .. lowerTarget,
        "i apologize for " .. lowerTarget,
        "i apologize to " .. lowerTarget .. " for",
        "sincere apologies for " .. lowerTarget,
        "deepest apologies for " .. lowerTarget,
        "my sincerest apologies for " .. lowerTarget,
        "i take full responsibility for " .. lowerTarget,
        "that's on me for " .. lowerTarget
    }
    
    for _, pattern in ipairs(apologyPatterns) do
        if string.find(lowerMessage, pattern) then
            return true
        end
    end
    
    local allApologyPatterns = {
        "my bad all",
        "mb all",
        "sorry all",
        "im sorry all",
        "i'm sorry all",
        "apologies all",
        "my apologies all",
        "excuse me all",
        "pardon all",
        "pardon me all",
        "forgive me all",
        "my mistake all",
        "oops all",
        "whoops all",
        "my fault all",
        "that was my fault all",
        "i messed up all",
        "i made a mistake all",
        "i goofed all",
        "i slipped all",
        "i missed all",
        "i was wrong all",
        "my error all",
        "i apologize all",
        "sincere apologies all",
        "deepest apologies all",
        "my sincerest apologies all",
        "i take full responsibility all",
        "that's on me all",
        "my bad everyone",
        "mb everyone",
        "sorry everyone",
        "im sorry everyone",
        "i'm sorry everyone",
        "apologies everyone",
        "my apologies everyone",
        "excuse me everyone",
        "pardon everyone",
        "pardon me everyone",
        "forgive me everyone",
        "my mistake everyone",
        "oops everyone",
        "whoops everyone",
        "my fault everyone",
        "that was my fault everyone",
        "i messed up everyone",
        "i made a mistake everyone",
        "i goofed everyone",
        "i slipped everyone",
        "i missed everyone",
        "i was wrong everyone",
        "my error everyone",
        "i apologize everyone",
        "sincere apologies everyone",
        "deepest apologies everyone",
        "my sincerest apologies everyone",
        "i take full responsibility everyone",
        "that's on me everyone",
        "my bad guys",
        "mb guys",
        "sorry guys",
        "im sorry guys",
        "i'm sorry guys",
        "apologies guys",
        "my apologies guys",
        "excuse me guys",
        "pardon guys",
        "pardon me guys",
        "forgive me guys",
        "my mistake guys",
        "oops guys",
        "whoops guys",
        "my fault guys",
        "that was my fault guys",
        "i messed up guys",
        "i made a mistake guys",
        "i goofed guys",
        "i slipped guys",
        "i missed guys",
        "i was wrong guys",
        "my error guys",
        "i apologize guys",
        "sincere apologies guys",
        "deepest apologies guys",
        "my sincerest apologies guys",
        "i take full responsibility guys",
        "that's on me guys"
    }
    
    for _, pattern in ipairs(allApologyPatterns) do
        if string.find(lowerMessage, pattern) then
            return "all"
        end
    end
    
    return false
end

return module
